// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyllpipdavyngmktkgsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5bGxwaXBkYXZ5bmdta3RrZ3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzQzMTMsImV4cCI6MjA2Njk1MDMxM30.bvPF1TU3YWgGq4BEfZdrZPlXaE1Z86_ejPpmeyXfnC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});